### ISSUE TITLE
Drum Machine Instructions

### ISSUE THREAD

**Issue by cbarber1984** [wesleydamasceno/master-code#1]
Drum machine problem section contains calculator instructions "Create a basic calculator that does simple operations."

contents/fundamentals/frontend/drum-machine/problem.md

**Comment by cbarber1984** [comment]
I've never contributed to an open source project so please accept any apologies if I'm violating protocols or community guidelines. I'd love to try my hand at the clone the repo, fix the typo, submit the PR process if that's ok.

**Comment by wesleydamasceno** [comment]
I'm very happy to have the error. Feel free to send your #PR 😄
