### ISSUE TITLE
Create page with problems-table for Web Issues (website)

### ISSUE THREAD

**Issue by wesleydamasceno** [wesleydamasceno/master-code#12]
Add second page in website:

- [x] Add web-issues links
- [x] Sort for type

**Comment by surrenderoz** [comment]
How I can contribute?

**Comment by wesleydamasceno** [comment]
Hello @surrenderoz, with issue #5 or with [Wiki](https://github.com/wesleydamasceno/master-code/wiki) contents. You can submit problems too in develop branch, with problem.md files

I have discord server, if you like that, here is the link: https://discord.gg/UvjMJpcMSv
